### PR TITLE
Update to fix infinite loop

### PR DESCRIPTION
**Pull request by mcdappdev**
This removes the package.pins file as well as gitignores it for the future. This will require a need release to go into effect, perhaps 2.1.

### CODE REVIEW

**Comment by mcdappdev** [comment]
Update, this doesn't seem to fix the problem. Still working on figuring out why.

**Comment by mcdappdev** [comment]
@vzsg and I discovered that the tag needs to be 2.0.0 to succeed.

**Comment by vzsg** [comment]
For the S3SignerAWS dependency, I'll open a PR to the original repo so pointing this package there will not be necessary.

**Comment by mcdappdev** [comment]
👍

**Pull request merged**
